apiVersion: v1
kind: Service
metadata:
  name: bug-hunter-svc
  namespace: codesentinel
  labels:
    app: bug-hunter
    app.kubernetes.io/part-of: codesentinel
spec:
  selector:
    app: bug-hunter
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  type: ClusterIP