apiVersion: v1
kind: Service
metadata:
  name: github-client-svc
  namespace: codesentinel
  labels:
    app: github-client
    app.kubernetes.io/part-of: codesentinel
spec:
  selector:
    app: github-client
  ports:
    - name: http
      port: 8006
      targetPort: 8006
  type: ClusterIP
